package dev.tramai.engine.tool

import dev.tramai.core.model.ToolResult
import dev.tramai.core.observation.ToolFailureDiagnosticEvent
import dev.tramai.core.observation.ToolFailureDiagnosticObserver
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.junit.jupiter.api.Test
import java.util.concurrent.atomic.AtomicInteger

class ToolCancellationContractTest {
    @Test fun `execution policy cancellation does not invoke tool`() { val calls = AtomicInteger(); val cancellation = CancellationException("auth"); assertThatThrownBy { runBlocking { ToolInvocationExecutor(ToolAuthorizationCoordinator(policyHelper { throw cancellation }), ToolRetryPolicy(), RecordingToolObserver(), ToolApprovalGate { _, _, _ -> }).execute(toolRequest(testTool { _, _ -> calls.incrementAndGet(); ToolResult.Success("bad") })) } }.isSameAs(cancellation); assertThat(calls.get()).isZero() }
    @Test fun `approval cancellation does not execute or classify`() { val calls = AtomicInteger(); val diagnostics = RecordingToolObserver(); val cancellation = CancellationException("approval"); assertThatThrownBy { runBlocking { ToolInvocationExecutor(ToolAuthorizationCoordinator(policyHelper { dev.tramai.core.policy.PolicyDecision.RequireApproval(dev.tramai.core.policy.ApprovalRequirement("test-tool", "d", "r", 1)) }), ToolRetryPolicy(), diagnostics, ToolApprovalGate { _, _, _ -> throw cancellation }).execute(toolRequest(testTool { _, _ -> calls.incrementAndGet(); ToolResult.Success("bad") })) } }.isSameAs(cancellation); assertThat(calls.get()).isZero(); assertThat(diagnostics.events).isEmpty() }
    @Test fun `tool cancellation creates no diagnostic`() { val diagnostics = RecordingToolObserver(); assertThatThrownBy { runBlocking { ToolInvocationExecutor(ToolAuthorizationCoordinator(policyHelper()), ToolRetryPolicy(), diagnostics, ToolApprovalGate { _, _, _ -> }).execute(toolRequest(testTool { _, _ -> throw CancellationException("tool") })) } }.isInstanceOf(CancellationException::class.java); assertThat(diagnostics.events).isEmpty() }
    @Test fun `active observer cancellation is fail open`() { runBlocking { val observer = object : ToolFailureDiagnosticObserver { override fun record(event: ToolFailureDiagnosticEvent) { throw CancellationException("observer") } }; val result = ToolInvocationExecutor(ToolAuthorizationCoordinator(policyHelper()), ToolRetryPolicy(), observer, ToolApprovalGate { _, _, _ -> }).execute(toolRequest(testTool { _, _ -> ToolResult.TransientFailure(RuntimeException()) })); assertThat(result).isInstanceOf(ToolResult.PermanentFailure::class.java) } }
    @Test fun `exposure cancellation propagates`() { val cancellation = CancellationException("exposure"); assertThatThrownBy { runBlocking { ToolExposureCoordinator(dev.tramai.engine.ToolRegistry(), policyHelper { throw cancellation }).enforce(toolOperation("x"), "cid", dev.tramai.engine.ExecutionSecurityContext()) } }.isSameAs(cancellation) }
    @Test fun `reinjection policy cancellation appends nothing`() { val messages = mutableListOf<dev.tramai.core.model.Message>(); val calls = AtomicInteger(); val cancellation = CancellationException("reinject"); val coordinator = ToolReinjectionCoordinator(dev.tramai.engine.ToolRegistry(mapOf("a" to testTool(name = "a", execute = { _, _ -> calls.incrementAndGet(); ToolResult.Success("ok") }))), policyHelper { throw cancellation }, ToolInvocationExecutor(ToolAuthorizationCoordinator(policyHelper()), ToolRetryPolicy(), RecordingToolObserver(), ToolApprovalGate { _, _, _ -> }), ToolResultSanitizer(dev.tramai.engine.ToolRegistry(), dev.tramai.core.security.NoOpDlpInterceptor, dev.tramai.core.security.NoOpDlpRedactionAuditEmitter, dev.tramai.engine.ToolResultFilteringSettings(), dev.tramai.engine.NoOpEngineEventObserver)); assertThatThrownBy { runBlocking { coordinator.process(ToolCallBatchRequest(toolOperation(), messages, listOf(dev.tramai.core.model.ToolCall("c1", "a", "{}")), "cid", dev.tramai.engine.ExecutionSecurityContext(), dev.tramai.engine.EngineExecutionIdentity("run", "cid", dev.tramai.core.approval.Sha256Digest.of("sha256:" + "a".repeat(64)), "v1", "actor"))) } }.isSameAs(cancellation); assertThat(messages).isEmpty(); assertThat(calls.get()).isEqualTo(1) }
    @Test fun `dlp inspection cancellation propagates unwrapped`() { val interceptor = object : dev.tramai.core.security.DlpInterceptor { override fun inspect(context: dev.tramai.core.security.DlpContext, text: String): dev.tramai.core.security.DlpResult { throw CancellationException("dlp") } }; val sanitizer = ToolResultSanitizer(dev.tramai.engine.ToolRegistry(), interceptor, dev.tramai.core.security.NoOpDlpRedactionAuditEmitter, dev.tramai.engine.ToolResultFilteringSettings(), dev.tramai.engine.NoOpEngineEventObserver); assertThatThrownBy { runBlocking { sanitizer.sanitize(dev.tramai.core.model.Message(role = dev.tramai.core.model.MessageRole.TOOL, content = "x", toolCallId = "c1"), toolOperation("x"), "a", "cid", dev.tramai.engine.ExecutionSecurityContext()) } }.isInstanceOf(CancellationException::class.java) }
}
