org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.paths=/home/gionag/.sdkman/candidates/java/25.0.2-open,/home/gionag/.sdkman/candidates/java/25.0.2-graalce
tramaiGroup=dev.tramai
tramaiVersion=0.1.0-SNAPSHOT
tramaiProjectUrl=https://github.com/gionag/tramai
tramaiScmUrl=https://github.com/gionag/tramai.git
tramaiScmConnection=scm:git:https://github.com/gionag/tramai.git
tramaiScmDeveloperConnection=scm:git:ssh://git@github.com/gionag/tramai.git
tramaiLicenseName=Apache-2.0
tramaiLicenseUrl=https://www.apache.org/licenses/LICENSE-2.0.txt
tramaiDeveloperId=gionag
tramaiDeveloperName=Giona
tramaiDeveloperEmail=opensource@giona.dev
