org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.paths=/home/gionag/.sdkman/candidates/java/25.0.2-open,/home/gionag/.sdkman/candidates/java/25.0.2-graalce
auroraGroup=io.aurora
auroraVersion=0.1.0-SNAPSHOT
auroraProjectUrl=https://github.com/gionag/aurora
auroraScmUrl=https://github.com/gionag/aurora.git
auroraScmConnection=scm:git:https://github.com/gionag/aurora.git
auroraScmDeveloperConnection=scm:git:ssh://git@github.com/gionag/aurora.git
auroraLicenseName=Apache-2.0
auroraLicenseUrl=https://www.apache.org/licenses/LICENSE-2.0.txt
auroraDeveloperId=gionag
auroraDeveloperName=Giona
auroraDeveloperEmail=opensource@giona.dev
