rootProject.name = "tramai"

include(
    "tramai-anthropic",
    "tramai-bom",
    "tramai-core",
    "tramai-embedding",
    "tramai-engine",
    "tramai-observability",
    "tramai-mcp",
    "tramai-orchestration",
    "tramai-openai",
    "tramai-ollama",
    "tramai-platform",
    "tramai-spring",
    "tramai-scheduler",
    "tramai-server",
    "tramai-standalone",
    "tramai-structured",
    "tramai-testing",
    "tramai-vectorstore-spi",
    "tramai-vectorstore-chroma",
    "tramai-vectorstore-pgvector",
    "tramai-dashboard",
    "tramai-rag",
    "examples:support-agent",
)
