create table if not exists platform_team (
    id varchar(128) primary key,
    name varchar(255) not null
);

create table if not exists platform_project (
    id varchar(128) primary key,
    team_id varchar(128) not null,
    name varchar(255) not null,
    constraint fk_platform_project_team
        foreign key (team_id) references platform_team(id)
);

create table if not exists platform_api_key (
    id varchar(128) primary key,
    team_id varchar(128) not null,
    project_id varchar(128) not null,
    prefix varchar(32) not null,
    hashed_key varchar(64) not null,
    name varchar(255) not null,
    scopes varchar(255) not null,
    burst_capacity integer not null,
    refill_tokens_per_second double precision not null,
    created_at timestamp not null,
    revoked_at timestamp null,
    last_used_at timestamp null,
    constraint fk_platform_api_key_team
        foreign key (team_id) references platform_team(id),
    constraint fk_platform_api_key_project
        foreign key (project_id) references platform_project(id),
    constraint uq_platform_api_key_prefix
        unique (prefix)
);

create index if not exists idx_platform_api_key_team_project
    on platform_api_key(team_id, project_id);

create table if not exists platform_audit_log (
    id bigint generated by default as identity primary key,
    timestamp timestamp not null,
    actor_id varchar(128) not null,
    action varchar(128) not null,
    resource_type varchar(128) not null,
    resource_id varchar(255) not null,
    team_id varchar(128) not null,
    metadata_json clob not null,
    constraint fk_platform_audit_team
        foreign key (team_id) references platform_team(id)
);

create index if not exists idx_platform_audit_team_action
    on platform_audit_log(team_id, action);

create table if not exists platform_plugin (
    id varchar(255) primary key,
    version varchar(64) not null,
    jar_path varchar(1024) not null,
    enabled boolean not null,
    status varchar(32) not null,
    error clob null,
    updated_at timestamp not null
);
