package dev.tramai.core.observation.event

/**
 * Compile-time references to every catalogue event definition.
 */
object RuntimeEvents {
    val WORKER_HEARTBEAT = RuntimeEventCatalogue.event("tramai.worker.heartbeat")
    val WORKER_LEASE_ACQUIRED = RuntimeEventCatalogue.event("tramai.worker.lease.acquired")
    val WORKER_LEASE_RELEASED = RuntimeEventCatalogue.event("tramai.worker.lease.released")
    val WORKER_LEASE_EXPIRED = RuntimeEventCatalogue.event("tramai.worker.lease.expired")
    val WORKER_LEASE_RENEWED = RuntimeEventCatalogue.event("tramai.worker.lease.renewed")
    val WORKER_LEASE_CONTESTED = RuntimeEventCatalogue.event("tramai.worker.lease.contested")
    val WORKER_LEASE_RENEWAL_FAILED = RuntimeEventCatalogue.event("tramai.worker.lease.renewal_failed")
    val WORKER_LEASE_RELEASE_FAILED = RuntimeEventCatalogue.event("tramai.worker.lease.release_failed")
    val WORKER_POLL_FAILED = RuntimeEventCatalogue.event("tramai.worker.poll.failed")
    val WORKER_WORK_TAKEN_OVER = RuntimeEventCatalogue.event("tramai.worker.work_taken_over")
    val WORKER_UNKNOWN_ATTEMPT = RuntimeEventCatalogue.event("tramai.worker.unknown_attempt")
    val WORKER_STEP_STARTED = RuntimeEventCatalogue.event("tramai.worker.step.started")
    val WORKER_STEP_COMPLETED = RuntimeEventCatalogue.event("tramai.worker.step.completed")
    val WORKER_STEP_FAILED = RuntimeEventCatalogue.event("tramai.worker.step.failed")
    val WORKER_SHUTDOWN_STARTED = RuntimeEventCatalogue.event("tramai.worker.shutdown.started")
    val WORKER_DRAIN_PROGRESS = RuntimeEventCatalogue.event("tramai.worker.drain.progress")
    val WORKER_SHUTDOWN_COMPLETE = RuntimeEventCatalogue.event("tramai.worker.shutdown.complete")
    val WORKER_WORKFLOW_ABANDONED = RuntimeEventCatalogue.event("tramai.worker.workflow.abandoned")
    val WORKFLOW_STEP_STARTED = RuntimeEventCatalogue.event("tramai.workflow.step.started")
    val WORKFLOW_STEP_COMPLETED = RuntimeEventCatalogue.event("tramai.workflow.step.completed")
    val WORKFLOW_STEP_FAILED = RuntimeEventCatalogue.event("tramai.workflow.step.failed")
    val ROUTE_SELECTED = RuntimeEventCatalogue.event("tramai.route.selected")
    val CIRCUIT_OPENED = RuntimeEventCatalogue.event("tramai.circuit.opened")
    val STREAMING_STARTUP_RETRY = RuntimeEventCatalogue.event("tramai.streaming.startup_retry")
    val RETRY_SCHEDULED = RuntimeEventCatalogue.event("tramai.retry.scheduled")
    val DLP_INSPECTION_FAILED = RuntimeEventCatalogue.event("tramai.dlp.inspection_failed")
    val DLP_TOOL_RESULT_REJECTED = RuntimeEventCatalogue.event("tramai.dlp.tool_result_rejected")
    val PARSE_FAILURE = RuntimeEventCatalogue.event("tramai.parse.failure")
    val APPROVAL_AUTHORIZATION_REPLAYED = RuntimeEventCatalogue.event("tramai.approval.authorization_replayed")
    val TOKEN_BUDGET_USAGE_UNAVAILABLE = RuntimeEventCatalogue.event("tramai.token_budget.usage_unavailable")
    val TOKEN_BUDGET_SOFT_LIMIT_EXCEEDED = RuntimeEventCatalogue.event("tramai.token_budget.soft_limit_exceeded")
    val TOKEN_BUDGET_HARD_LIMIT_EXCEEDED = RuntimeEventCatalogue.event("tramai.token_budget.hard_limit_exceeded")
    val WORKFLOW_SECURITY_STEP_EXECUTED = RuntimeEventCatalogue.event("tramai.workflow.security.step_executed")
    val WORKFLOW_SECURITY_OUTPUT_REJECTED = RuntimeEventCatalogue.event("tramai.workflow.security.output_rejected")
    val WORKFLOW_SECURITY_SANITIZER_TRIGGERED = RuntimeEventCatalogue.event("tramai.workflow.security.sanitizer_triggered")
    val WORKFLOW_SECURITY_COMMAND_DENIED = RuntimeEventCatalogue.event("tramai.workflow.security.command_denied")
    val WORKFLOW_DELAY_STARTED = RuntimeEventCatalogue.event("tramai.workflow.delay.started")
    val WORKFLOW_DELAY_WAITING = RuntimeEventCatalogue.event("tramai.workflow.delay.waiting")
    val WORKFLOW_DELAY_RESUMED = RuntimeEventCatalogue.event("tramai.workflow.delay.resumed")
    val WORKFLOW_HTTP_VALIDATION_FAILED = RuntimeEventCatalogue.event("tramai.workflow.http.request.validation.failed")
    val WORKFLOW_HTTP_POLICY_REJECTED = RuntimeEventCatalogue.event("tramai.workflow.http.request.policy.rejected")
    val WORKFLOW_HTTP_STARTED = RuntimeEventCatalogue.event("tramai.workflow.http.request.started")
    val WORKFLOW_HTTP_COMPLETED = RuntimeEventCatalogue.event("tramai.workflow.http.request.completed")
    val WORKFLOW_HTTP_RETRYING = RuntimeEventCatalogue.event("tramai.workflow.http.request.retrying")
    val WORKFLOW_HTTP_TRUNCATED = RuntimeEventCatalogue.event("tramai.workflow.http.response.truncated")
    val WORKFLOW_MCP_STARTED = RuntimeEventCatalogue.event("tramai.workflow.mcp.started")
    val WORKFLOW_MCP_COMPLETED = RuntimeEventCatalogue.event("tramai.workflow.mcp.completed")
    val WORKFLOW_MCP_RECONNECTING = RuntimeEventCatalogue.event("tramai.workflow.mcp.reconnecting")
    val WORKFLOW_CODEX_STARTED = RuntimeEventCatalogue.event("tramai.workflow.codex.started")
    val WORKFLOW_CODEX_COMPLETED = RuntimeEventCatalogue.event("tramai.workflow.codex.completed")
    val WORKFLOW_HERMES_STARTED = RuntimeEventCatalogue.event("tramai.workflow.hermes.started")
    val WORKFLOW_HERMES_COMPLETED = RuntimeEventCatalogue.event("tramai.workflow.hermes.completed")
    val WORKFLOW_SHELL_STARTED = RuntimeEventCatalogue.event("tramai.workflow.shell.started")
    val WORKFLOW_SHELL_COMPLETED = RuntimeEventCatalogue.event("tramai.workflow.shell.completed")
    val WORKFLOW_SHELL_TIMEOUT = RuntimeEventCatalogue.event("tramai.workflow.shell.timeout")
    val WORKFLOW_SHELL_TRUNCATED = RuntimeEventCatalogue.event("tramai.workflow.shell.truncated")
    val WORKFLOW_CHECKPOINT_SAVED = RuntimeEventCatalogue.event("tramai.workflow.checkpoint.saved")
    val WORKFLOW_CHECKPOINT_LOADED = RuntimeEventCatalogue.event("tramai.workflow.checkpoint.loaded")
    val WORKFLOW_SUSPENDED = RuntimeEventCatalogue.event("tramai.workflow.suspended")
    val WORKFLOW_LEASE_CLAIMED = RuntimeEventCatalogue.event("tramai.workflow.lease.claimed")
    val WORKFLOW_LEASE_RENEWED = RuntimeEventCatalogue.event("tramai.workflow.lease.renewed")
    val WORKFLOW_LEASE_RELEASED = RuntimeEventCatalogue.event("tramai.workflow.lease.released")
    val WORKFLOW_LEASE_CONFLICT = RuntimeEventCatalogue.event("tramai.workflow.lease.conflict")
}
