package dev.tramai.orchestration

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.DisposableHandle
import kotlinx.coroutines.InternalCoroutinesApi
import kotlinx.coroutines.Job
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.runInterruptible
import kotlinx.coroutines.withContext
import dev.tramai.core.coroutines.rethrowIfCancellation
import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicReference
import javax.sql.DataSource

/**
 * Tracks the active [Statement] for a single JDBC operation so that
 * [requestCancellation] can be called when the coroutine is cancelled.
 *
 * This class deliberately does NOT expose a `connection` property so that
 * call sites always use the tracked proxy passed as the lambda parameter.
 */
internal class JdbcOperationContext {
    private val activeStatement = AtomicReference<Statement?>(null)
    private val cancellationRequested = AtomicBoolean(false)
    private val cancellationFailure = AtomicReference<Throwable?>(null)

    /**
     * Register a statement for cancellation.
     *
     * Attaches first, then double-checks the cancellation flag using
     * compare-and-set. This prevents a TOCTOU race where the statement
     * is recorded after [requestCancellation] already ran and found no
     * active statement.
     */
    fun attachStatement(statement: Statement) {
        activeStatement.set(statement)
        if (
            cancellationRequested.get() &&
            activeStatement.compareAndSet(statement, null)
        ) {
            cancelStatement(statement)
        }
    }

    /**
     * Cancel the currently active statement (if any) and remember that
     * cancellation has been requested so any subsequently attached statements
     * are cancelled immediately.
     */
    fun requestCancellation() {
        cancellationRequested.set(true)
        activeStatement.getAndSet(null)?.let(::cancelStatement)
    }

    /**
     * Returns `true` if [requestCancellation] has been called, meaning
     * the coroutine was cancelled and the handler fired.
     */
    fun isCancellationRequested(): Boolean = cancellationRequested.get()

    /**
     * Returns any failure from [Statement.cancel] that was captured during
     * cancellation, or `null` if cancellation succeeded or was not triggered.
     */
    fun takeCancellationFailure(): Throwable? =
        cancellationFailure.getAndSet(null)

    private fun cancelStatement(statement: Statement) {
        try {
            statement.cancel()
        } catch (failure: SQLException) {
            cancellationFailure.compareAndSet(null, failure)
        }
    }
}

/**
 * Roll back [connection] under [NonCancellable], suppressing any
 * [SQLException] from the rollback onto [primary].
 */
private suspend fun rollbackSuppressing(connection: Connection, primary: Throwable) {
    withContext(NonCancellable + Dispatchers.IO) {
        try {
            runInterruptible { connection.rollback() }
        } catch (rollbackFailure: SQLException) {
            primary.addSuppressed(rollbackFailure)
        }
    }
}

/**
 * Wraps a [Connection] so that every [prepareStatement] and [createStatement] call
 * automatically registers the statement with [ctx] for cancellation.
 */
private fun Connection.trackedConnection(ctx: JdbcOperationContext): Connection {
    val delegate = this
    return object : Connection by delegate {
        override fun prepareStatement(sql: String): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(
            sql: String,
            resultSetType: Int,
            resultSetConcurrency: Int,
        ): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(sql: String, autoGeneratedKeys: Int): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, autoGeneratedKeys)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(
            sql: String,
            resultSetType: Int,
            resultSetConcurrency: Int,
            resultSetHoldability: Int,
        ): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(sql: String, columnIndexes: IntArray): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, columnIndexes)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(sql: String, columnNames: Array<out String>): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, columnNames)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun createStatement(): java.sql.Statement {
            val stmt = delegate.createStatement()
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): java.sql.Statement {
            val stmt = delegate.createStatement(resultSetType, resultSetConcurrency)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun createStatement(
            resultSetType: Int,
            resultSetConcurrency: Int,
            resultSetHoldability: Int,
        ): java.sql.Statement {
            val stmt = delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability)
            ctx.attachStatement(stmt)
            return stmt
        }
    }
}

/**
 * Execute [block] with a JDBC connection obtained from [dataSource], supporting
 * coroutine cancellation at any point.
 *
 * * All blocking JDBC operations run on [Dispatchers.IO] with [runInterruptible].
 * * Connection acquisition (`dataSource.connection`) runs inside [runInterruptible].
 * * Auto-commit setup (getting/setting) runs inside the protected try/finally block
 *   so that connection leaks are not possible regardless of failure timing.
 * * Before the blocking call, an [invokeOnCompletion] handle is registered so that
 *   [JdbcOperationContext.requestCancellation] fires **before** the blocking operation
 *   returns — this calls [Statement.cancel] on the active statement concurrently even
 *   when the JDBC driver ignores thread interruption.
 * * On cancellation: [Statement.cancel] failure is suppressed, transaction rollback
 *   runs under [NonCancellable], and rollback failures are suppressed.
 * * On any non-cancellation failure: rollback runs, failures are suppressed.
 * * Final cleanup (auto-commit restore, connection close) runs under [NonCancellable];
 *   close() is always attempted even when auto-commit restoration fails. All cleanup
 *   failures are suppressed onto the primary exception when one exists, or thrown
 *   directly on the success path.
 * * The block parameter is a [Connection] proxy that auto-registers statements;
 *   there is no receiver so accidental raw-connection access is not representable.
 */
@OptIn(InternalCoroutinesApi::class)
internal suspend fun <T> executeJdbcCancellable(
    dataSource: DataSource,
    transactional: Boolean = false,
    block: (Connection) -> T,
): T {
    // Capture the parent Job before withContext so the cancellation handler
    // is registered on the correct job (not the internally managed one).
    val parentJob = currentCoroutineContext()[Job]
    return withContext(Dispatchers.IO) {
    val connection = runInterruptible(Dispatchers.IO) {
        dataSource.connection
    }
    val ctx = JdbcOperationContext()
    val wrappedConnection = connection.trackedConnection(ctx)

    // Everything from here enters the protected region so the finally block
    // always runs — connection leaks are not possible.
    var previousAutoCommit: Boolean? = null
    var cancellationHandle: DisposableHandle? = null
    val primaryFailure = AtomicReference<Throwable?>(null)

    try {
        if (transactional) {
            previousAutoCommit = runInterruptible {
                connection.autoCommit.also { connection.autoCommit = false }
            }
        }

        // Register a handle that fires on cancellation BEFORE the blocking call returns.
        cancellationHandle = parentJob?.invokeOnCompletion(onCancelling = true) { cause ->
            if (cause is CancellationException) {
                ctx.requestCancellation()
            }
        }

        val result = runInterruptible {
            block(wrappedConnection)
        }
        if (transactional) {
            runInterruptible {
                ensureActive()
                connection.commit()
            }
        }
        result
    } catch (e: CancellationException) {
        ctx.takeCancellationFailure()?.let(e::addSuppressed)
        if (transactional) {
            rollbackSuppressing(connection, e)
        }
        primaryFailure.set(e)
        throw e
    } catch (e: Exception) {
        // Scanner-required: rethrow cancellation before processing.
        e.rethrowIfCancellation()
        // For non-cancellation failures, check whether the coroutine was
        // cancelled but the JDBC driver responded with SQLException.
        // Use ensureActive which reliably detects cancellation regardless
        // of which Job is in the context.
        var wasCancelled = ctx.isCancellationRequested()
        if (!wasCancelled) {
            try {
                ensureActive()
            } catch (_: CancellationException) {
                wasCancelled = true
            }
        }
        if (wasCancelled) {
            val cancellation = CancellationException(
                "Operation was cancelled while executing JDBC operation",
            )
            cancellation.addSuppressed(e)
            ctx.takeCancellationFailure()?.let(cancellation::addSuppressed)
            primaryFailure.set(cancellation)
            if (transactional) {
                rollbackSuppressing(connection, cancellation)
            }
            throw cancellation
        }

        primaryFailure.set(e)
        if (transactional) {
            rollbackSuppressing(connection, e)
        }
        throw e
    } finally {
        cancellationHandle?.dispose()
        withContext(NonCancellable + Dispatchers.IO) {
            runInterruptible {
                // Collect cleanup failures without skipping close().
                // Always attempt close() even when auto-commit restoration fails.
                var cleanupFailure: SQLException? = null

                try {
                    if (transactional && previousAutoCommit != null) {
                        connection.autoCommit = previousAutoCommit
                    }
                } catch (failure: SQLException) {
                    cleanupFailure = failure
                }

                try {
                    connection.close()
                } catch (failure: SQLException) {
                    if (cleanupFailure == null) {
                        cleanupFailure = failure
                    } else {
                        cleanupFailure.addSuppressed(failure)
                    }
                }

                cleanupFailure?.let { failure ->
                    val primary = primaryFailure.get()
                    if (primary != null) {
                        primary.addSuppressed(failure)
                    } else {
                        throw failure
                    }
                }
            }
        }
    }
}
}
