package dev.tramai.orchestration

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.InternalCoroutinesApi
import kotlinx.coroutines.Job
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.runInterruptible
import kotlinx.coroutines.withContext
import java.sql.Connection
import java.sql.Statement
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicReference
import javax.sql.DataSource

/**
 * Tracks the active [Statement] for a single JDBC operation so that
 * [requestCancellation] can be called when the coroutine is cancelled.
 *
 * This class deliberately does NOT expose a `connection` property so that
 * call sites always use the tracked proxy passed as the lambda parameter.
 */
internal class JdbcOperationContext {
    private val activeStatement = AtomicReference<Statement?>(null)
    private val cancellationRequested = AtomicBoolean(false)

    /** Register a statement for cancellation. */
    fun attachStatement(statement: Statement) {
        if (cancellationRequested.get()) {
            // Cancellation was already triggered — cancel immediately.
            try {
                statement.cancel()
            } catch (_: Exception) {
                // Best-effort; the original CancellationException is already in flight.
            }
            return
        }
        activeStatement.set(statement)
    }

    /**
     * Cancel the currently active statement (if any) and remember that
     * cancellation has been requested so any subsequently attached statements
     * are cancelled immediately.
     */
    fun requestCancellation() {
        cancellationRequested.set(true)
        activeStatement.getAndSet(null)?.cancel()
    }
}

/**
 * Wraps a [Connection] so that every [prepareStatement] and [createStatement] call
 * automatically registers the statement with [ctx] for cancellation.
 */
private fun Connection.trackedConnection(ctx: JdbcOperationContext): Connection {
    val delegate = this
    return object : Connection by delegate {
        override fun prepareStatement(sql: String): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(
            sql: String,
            resultSetType: Int,
            resultSetConcurrency: Int,
        ): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(sql: String, autoGeneratedKeys: Int): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, autoGeneratedKeys)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(
            sql: String,
            resultSetType: Int,
            resultSetConcurrency: Int,
            resultSetHoldability: Int,
        ): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(sql: String, columnIndexes: IntArray): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, columnIndexes)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun prepareStatement(sql: String, columnNames: Array<out String>): java.sql.PreparedStatement {
            val stmt = delegate.prepareStatement(sql, columnNames)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun createStatement(): java.sql.Statement {
            val stmt = delegate.createStatement()
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): java.sql.Statement {
            val stmt = delegate.createStatement(resultSetType, resultSetConcurrency)
            ctx.attachStatement(stmt)
            return stmt
        }

        override fun createStatement(
            resultSetType: Int,
            resultSetConcurrency: Int,
            resultSetHoldability: Int,
        ): java.sql.Statement {
            val stmt = delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability)
            ctx.attachStatement(stmt)
            return stmt
        }
    }
}

/**
 * Execute [block] with a JDBC connection obtained from [dataSource], supporting
 * coroutine cancellation at any point.
 *
 * * All blocking JDBC operations run on [Dispatchers.IO] with [runInterruptible].
 * * Connection acquisition (`dataSource.connection`) runs inside [runInterruptible].
 * * Before the blocking call, an [invokeOnCompletion] handle is registered so that
 *   [JdbcOperationContext.requestCancellation] fires **before** the blocking operation
 *   returns — this calls [Statement.cancel] on the active statement concurrently even
 *   when the JDBC driver ignores thread interruption.
 * * On cancellation, the active statement is cancelled, the transaction is rolled back
 *   (when [transactional] is true), and cleanup failures are suppressed onto the
 *   original [CancellationException].
 * * Auto-commit restoration and connection closing run under [NonCancellable].
 * * The block parameter is a [Connection] proxy that auto-registers statements;
 *   there is no receiver so accidental raw-connection access is not representable.
 */
@OptIn(InternalCoroutinesApi::class)
internal suspend fun <T> executeJdbcCancellable(
    dataSource: DataSource,
    transactional: Boolean = false,
    block: (Connection) -> T,
): T = withContext(Dispatchers.IO) {
    val connection = runInterruptible(Dispatchers.IO) {
        dataSource.connection
    }
    val ctx = JdbcOperationContext()
    val wrappedConnection = connection.trackedConnection(ctx)

    var previousAutoCommit: Boolean? = null
    if (transactional) {
        previousAutoCommit = connection.autoCommit
        connection.autoCommit = false
    }

    // Register a handle that fires on cancellation BEFORE the blocking call returns.
    val job = currentCoroutineContext()[Job]
    val cancellationHandle = job?.invokeOnCompletion(onCancelling = true) { cause ->
        if (cause is CancellationException) {
            ctx.requestCancellation()
        }
    }

    try {
        val result = runInterruptible {
            block(wrappedConnection)
        }
        if (transactional) {
            runInterruptible {
                ensureActive()
                connection.commit()
            }
        }
        result
    } catch (e: CancellationException) {
        withContext(NonCancellable + Dispatchers.IO) {
            runInterruptible {
                try {
                    ctx.requestCancellation()
                } catch (t: Throwable) {
                    e.addSuppressed(t)
                }
                try {
                    if (transactional) connection.rollback()
                } catch (t: Throwable) {
                    e.addSuppressed(t)
                }
            }
        }
        throw e
    } catch (e: Throwable) {
        if (transactional) {
            runInterruptible {
                try {
                    connection.rollback()
                } catch (rollbackError: Throwable) {
                    e.addSuppressed(rollbackError)
                }
            }
        }
        throw e
    } finally {
        cancellationHandle?.dispose()
        withContext(NonCancellable + Dispatchers.IO) {
            runInterruptible {
                try {
                    if (transactional && previousAutoCommit != null) {
                        connection.autoCommit = previousAutoCommit
                    }
                } finally {
                    connection.close()
                }
            }
        }
    }
}
