package dev.tramai.orchestration

import java.io.IOException
import java.io.PrintWriter
import java.nio.file.Files
import java.nio.file.Path
import java.sql.Connection
import java.sql.DatabaseMetaData
import java.sql.PreparedStatement
import java.sql.SQLException
import java.util.logging.Logger
import javax.sql.DataSource
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.catchThrowable
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

/**
 * Adversarial leak tests for the persistence safe-failure boundary (PR #225).
 *
 * The invariant: filesystem paths, SQL text, persisted payloads, and arbitrary
 * exception messages never cross from persistence internals into public
 * exceptions, ordinary observers, or logs. The original failure reaches only
 * [PersistenceFailureDiagnosticObserver]; cancellation stays cancellation.
 *
 * Secret fixtures use the value `fixture-sentinel-7f3c` (GitGuardian-safe:
 * no credential-shaped keys). Assertions scan message + cause + EVERY
 * suppressed throwable + observer events.
 */
class PersistenceSafeFailureBoundaryTest {

    @TempDir
    lateinit var tempDir: Path

    private companion object {
        const val SECRET_SQL = "UPDATE tramai_workflow SET state_payload = 'fixture-sentinel-7f3c'"
        const val SECRET_PATH = "/home/customer/acme/private/fixture-sentinel-7f3c/workflow"
        const val SECRET_PAYLOAD = "fixture-sentinel-7f3c-persisted-state"
        const val SECRET_VALUE = "fixture-sentinel-7f3c-value"
    }

    private class RecordingPersistenceObserver : PersistenceFailureDiagnosticObserver {
        val events = mutableListOf<PersistenceFailureDiagnosticEvent>()
        var throwAfterRecording: Throwable? = null
        var throwFakeCancellation: Boolean = false

        override suspend fun onFailure(event: PersistenceFailureDiagnosticEvent) {
            events += event
            if (throwFakeCancellation) throw CancellationException("synthetic observer cancellation")
            throwAfterRecording?.let { throw it }
        }
    }

    private fun assertNoSecret(t: Throwable?, secret: String, seen: MutableSet<Throwable> = mutableSetOf()) {
        if (t == null || !seen.add(t)) return
        assertThat(t.message).doesNotContain(secret)
        assertThat(t.toString()).doesNotContain(secret)
        assertNoSecret(t.cause, secret, seen)
        t.suppressed.forEach { assertNoSecret(it, secret, seen) }
    }

    /** DataSource whose Connection throws a seeded SQLException on any statement. */
    private class SeededSqlDataSource(
        private val failure: SQLException,
    ) : DataSource {
        override fun getConnection(): Connection = ThrowingConnection(failure)
        override fun getConnection(username: String?, password: String?): Connection = ThrowingConnection(failure)
        override fun getLogWriter(): PrintWriter? = null
        override fun setLogWriter(out: PrintWriter?) = Unit
        override fun setLoginTimeout(seconds: Int) = Unit
        override fun getLoginTimeout(): Int = 0
        override fun getParentLogger(): Logger = Logger.getGlobal()
        override fun <T : Any?> unwrap(iface: Class<T>?): T = throw SQLException("Unsupported")
        override fun isWrapperFor(iface: Class<*>?): Boolean = false
    }

    private class ThrowingConnection(
        private val failure: SQLException,
    ) : Connection {
        override fun prepareStatement(sql: String): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, columnIndexes: IntArray?): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, columnNames: Array<out String>?): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): PreparedStatement = throw failure
        override fun prepareCall(sql: String): java.sql.CallableStatement = throw failure
        override fun prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): java.sql.CallableStatement = throw failure
        override fun prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): java.sql.CallableStatement = throw failure
        override fun createStatement(): java.sql.Statement = throw failure
        override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): java.sql.Statement = throw failure
        override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): java.sql.Statement = throw failure
        override fun nativeSQL(sql: String?): String = throw failure
        override fun setAutoCommit(autoCommit: Boolean) = Unit
        override fun getAutoCommit(): Boolean = true
        override fun commit() = Unit
        override fun rollback() = Unit
        override fun close() = Unit
        override fun isClosed(): Boolean = false
        override fun setReadOnly(readOnly: Boolean) = Unit
        override fun isReadOnly(): Boolean = true
        override fun setCatalog(catalog: String?) = Unit
        override fun getCatalog(): String? = null
        override fun setTransactionIsolation(level: Int) = Unit
        override fun getTransactionIsolation(): Int = Connection.TRANSACTION_READ_COMMITTED
        override fun getWarnings(): java.sql.SQLWarning? = null
        override fun clearWarnings() = Unit
        override fun setTypeMap(map: MutableMap<String, Class<*>>?) = Unit
        override fun getTypeMap(): MutableMap<String, Class<*>> = mutableMapOf()
        override fun setHoldability(holdability: Int) = Unit
        override fun getHoldability(): Int = java.sql.ResultSet.HOLD_CURSORS_OVER_COMMIT
        override fun setSavepoint(): java.sql.Savepoint = throw failure
        override fun setSavepoint(name: String?): java.sql.Savepoint = throw failure
        override fun rollback(savepoint: java.sql.Savepoint?) = Unit
        override fun releaseSavepoint(savepoint: java.sql.Savepoint?) = Unit
        override fun createClob(): java.sql.Clob = throw failure
        override fun createBlob(): java.sql.Blob = throw failure
        override fun createNClob(): java.sql.NClob = throw failure
        override fun createSQLXML(): java.sql.SQLXML = throw failure
        override fun isValid(timeout: Int): Boolean = true
        override fun setClientInfo(name: String?, value: String?) = Unit
        override fun setClientInfo(properties: java.util.Properties?) = Unit
        override fun getClientInfo(name: String?): String? = null
        override fun getClientInfo(): java.util.Properties = java.util.Properties()
        override fun createArrayOf(typeName: String?, elements: Array<out Any>?): java.sql.Array = throw failure
        override fun createStruct(typeName: String?, attributes: Array<out Any>?): java.sql.Struct = throw failure
        override fun setSchema(schema: String?) = Unit
        override fun getSchema(): String? = null
        override fun abort(executor: java.util.concurrent.Executor?) = Unit
        override fun setNetworkTimeout(executor: java.util.concurrent.Executor?, milliseconds: Int) = Unit
        override fun getNetworkTimeout(): Int = 0
        override fun getMetaData(): DatabaseMetaData = throw failure
        override fun <T : Any?> unwrap(iface: Class<T>?): T = throw SQLException("Unsupported")
        override fun isWrapperFor(iface: Class<*>?): Boolean = false
    }

    // --- 1. JDBC secret SQL reaches observer only ---

    @Test
    fun `raw jdbc exception containing secret sql reaches observer but not public exception`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val store = JdbcWorkflowCheckpointStore(SeededSqlDataSource(SQLException(SECRET_SQL)))
            store.persistenceFailureDiagnosticObserver = observer

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(observer.events).hasSize(1)
            val event = observer.events.single()
            assertThat(event.resourceKind).isEqualTo(PersistenceResourceKind.CHECKPOINT)
            assertThat(event.operation).isEqualTo(PersistenceOperation.SAVE)
            assertThat(event.failureCode).isEqualTo(PersistenceFailureCode.WRITE_FAILED)
            assertThat(event.failure.message).contains(SECRET_SQL)
        }
    }

    // --- 2. File exception secret path reaches observer only ---

    @Test
    fun `file exception containing secret path reaches observer but not public exception`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val failingWriter = AtomicFileWriter { _ -> throw IOException(SECRET_PATH) }
            val store = FileWorkflowCheckpointStore.forTest(tempDir, failingWriter)
            store.persistenceFailureDiagnosticObserver = observer

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_PATH)
            assertThat(observer.events).hasSize(1)
            assertThat(observer.events.single().failure.message).contains(SECRET_PATH)
        }
    }

    // --- 3. Corrupt checkpoint secret payload reaches observer only ---

    @Test
    fun `corrupt checkpoint containing secret payload reaches observer but not public exception`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val store = FileWorkflowCheckpointStore(tempDir)
            store.persistenceFailureDiagnosticObserver = observer
            // Write a checkpoint file whose recovery state decodes to garbage carrying the secret.
            val checkpointDir = tempDir.resolve("wf").resolve("run-1").toFile()
            checkpointDir.mkdirs()
            Files.writeString(
                tempDir.resolve("wf").resolve("run-1").resolve("checkpoint.properties"),
                "workflowName=wf\nworkflowId=run-1\nnextStepIndex=0\nstepExecutions=0\nstatePayloadBase64=c3RhdGU=\nrevision=1\nrecoveryState=${base64Encode(SECRET_PAYLOAD)}\n",
            )

            val thrown = catchThrowable {
                runBlocking { store.load("wf", "run-1") }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointCorruptionException::class.java)
            assertNoSecret(thrown, SECRET_PAYLOAD)
            assertThat(observer.events).hasSize(1)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.CORRUPTED_DATA)
        }
    }

    // --- 4. Corrupt step-attempt record secret value reaches observer only ---

    @Test
    fun `corrupt step attempt record containing secret value reaches observer but not public exception`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val store = FileStepAttemptRecordStore.forTest(tempDir, realAtomicFileWriter)
            store.persistenceFailureDiagnosticObserver = observer
            // Seed one record then corrupt its status to an unknown value carrying the secret.
            val record = minimalAttempt()
            store.recordStepAttempt(record)
            val attemptPath = tempDir
                .resolve(base64UrlEncodeNoPadding(record.runId))
                .resolve(base64UrlEncodeNoPadding(record.stepName))
                .resolve(base64UrlEncodeNoPadding(record.attemptId) + ".attempt.properties")
            val raw = Files.readString(attemptPath)
            Files.writeString(attemptPath, raw.replace("status=STARTED", "status=$SECRET_VALUE"))

            val thrown = catchThrowable {
                runBlocking { store.listStepAttempts(record.runId) }
            }

            assertThat(thrown).isInstanceOf(StepAttemptRecordCorruptionException::class.java)
            assertNoSecret(thrown, SECRET_VALUE)
            assertThat(observer.events).hasSize(1)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.CORRUPTED_DATA)
        }
    }

    // --- 5. Untrusted caller-constructed domain exception is re-sanitized ---

    @Test
    fun `caller constructed untrusted domain exception is re sanitized`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val untrusted = WorkflowCheckpointCorruptionException("password=fixture-sentinel-7f3c")

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(
                        PersistenceResourceKind.CHECKPOINT,
                        PersistenceOperation.LOAD,
                        observer,
                    ) { throw untrusted }
                }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointCorruptionException::class.java)
            assertThat(thrown).isNotSameAs(untrusted)
            assertNoSecret(thrown, "password=")
            assertNoSecret(thrown, "fixture-sentinel-7f3c")
            assertThat(observer.events).hasSize(1)
            assertThat(observer.events.single().failure).isSameAs(untrusted)
        }
    }

    // --- 6. Trusted safe exception passes through unchanged ---

    @Test
    fun `trusted safe exception passes through unchanged`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val safe = safePersistenceFailure(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.SAVE,
                PersistenceFailureCode.CONFLICT,
            )

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(
                        PersistenceResourceKind.CHECKPOINT,
                        PersistenceOperation.SAVE,
                        observer,
                    ) { throw safe }
                }
            }

            assertThat(thrown).isSameAs(safe)
            assertThat(observer.events).isEmpty()
        }
    }

    // --- 7. Observer ordinary failure is fail-open ---

    @Test
    fun `observer ordinary failure is fail open`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            observer.throwAfterRecording = IllegalStateException("observer bug")
            val store = JdbcWorkflowCheckpointStore(SeededSqlDataSource(SQLException(SECRET_SQL)))
            store.persistenceFailureDiagnosticObserver = observer

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(observer.events).hasSize(1)
        }
    }

    // --- 8. Synthetic observer cancellation while active is swallowed ---

    @Test
    fun `synthetic observer cancellation while active does not replace failure`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            observer.throwFakeCancellation = true
            val store = JdbcWorkflowCheckpointStore(SeededSqlDataSource(SQLException(SECRET_SQL)))
            store.persistenceFailureDiagnosticObserver = observer

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(observer.events).hasSize(1)
        }
    }

    // --- 9. Genuine parent cancellation stays primary, emits no diagnostic ---

    @Test
    fun `genuine parent cancellation remains primary and emits no diagnostic`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val entered = CompletableDeferred<Unit>()
            val release = CompletableDeferred<Unit>()

            val outer = CoroutineScope(Job())
            val outcome = CompletableDeferred<Throwable?>()
            outer.launch {
                try {
                    persistenceBoundary(
                        PersistenceResourceKind.CHECKPOINT,
                        PersistenceOperation.SAVE,
                        observer,
                    ) {
                        entered.complete(Unit)
                        release.await()
                        Unit
                    }
                    outcome.complete(null)
                } catch (t: Throwable) {
                    outcome.complete(t)
                }
            }
            entered.await()
            outer.coroutineContext[Job]!!.cancel()
            release.complete(Unit)
            val terminal = withTimeout(5_000) { outcome.await() }
            assertThat(terminal).isInstanceOf(CancellationException::class.java)
            assertThat(observer.events).isEmpty()
        }
    }

    // --- 10. Checkpoint conflict keeps its semantic class ---

    @Test
    fun `checkpoint conflict remains the correct semantic exception class`() {
        runBlocking {
            val store = InMemoryWorkflowCheckpointStore()
            store.save(testCheckpoint())

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointConflictException::class.java)
            assertThat((thrown as WorkflowCheckpointConflictException).message).isEqualTo("Workflow checkpoint conflict")
            assertThat((thrown as WorkflowCheckpointConflictException).cause).isNull()
        }
    }

    // --- 11. CAS and revision behavior unchanged ---

    @Test
    fun `cas and revision behavior unchanged`() {
        runBlocking {
            val store = InMemoryWorkflowCheckpointStore()
            val first = store.save(testCheckpoint())
            assertThat(first.revision).isEqualTo(1)

            val second = store.save(first, expectedRevision = first.revision)
            assertThat(second.revision).isEqualTo(2)

            val conflict = catchThrowable {
                runBlocking { store.save(second, expectedRevision = first.revision) }
            }
            assertThat(conflict).isInstanceOf(WorkflowCheckpointConflictException::class.java)

            val attemptStore = store as StepAttemptRecordStore
            val attempt = minimalAttempt()
            attemptStore.recordStepAttempt(attempt)
            assertThat(attemptStore.compareAndSetStepAttempt(attempt, attempt.copy(workerId = "w2"))).isTrue()
            assertThat(attemptStore.compareAndSetStepAttempt(attempt, attempt.copy(workerId = "w3"))).isFalse()
        }
    }

    // --- 12. Worker onPollFailed receives only the safe failure ---

    @Test
    fun `worker onPollFailed receives only safe failure`() {
        val pollFailures = mutableListOf<Throwable>()
        val workerObserver = object : TramaiWorkerObserver {
            override fun onPollFailed(workerId: String, error: Throwable) {
                pollFailures += error
            }
        }
        val failingCatalog = FailingCheckpointCatalog(SQLException(SECRET_SQL))
        val checkpointStore = InMemoryWorkflowCheckpointStore()

        val worker = TramaiWorker(
            config = WorkerConfig(
                workerId = "worker-secret-test",
                poolName = "tests",
                pollIntervalMillis = 20,
                leaseDurationMillis = 200,
                drainTimeoutMillis = 1_000,
                partitionEnabled = false,
                workerCount = 1,
            ),
            leaseStore = InMemoryWorkflowLeaseStore(),
            checkpointStore = checkpointStore,
            checkpointCatalog = failingCatalog,
            stepAttemptStore = checkpointStore,
            workflowRegistry = emptyMap(),
            observability = workerObserver,
        )
        runBlocking {
            worker.start()
            try {
                withTimeout(5_000) {
                    while (pollFailures.isEmpty() && currentCoroutineContext().isActive) delay(20)
                }
            } finally {
                worker.shutdown()
            }
        }

        assertThat(pollFailures).isNotEmpty()
        pollFailures.forEach { failure ->
            assertThat(failure).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(failure, SECRET_SQL)
        }
    }

    // --- 13. Logging observer renders class name only ---

    @Test
    fun `logging observer renders no raw error message`() {
        val logged = mutableListOf<String>()
        val observer = LoggingTramaiWorkerObserver { logged += it }
        observer.onPollFailed("w", SQLException(SECRET_SQL))
        observer.onLeaseRenewalFailed("wf", "w", IOException(SECRET_PATH))
        assertThat(logged.joinToString("\n")).doesNotContain(SECRET_SQL)
        assertThat(logged.joinToString("\n")).doesNotContain(SECRET_PATH)
    }

    // --- 14. Fixed public messages are stable ---

    @Test
    fun `fixed public messages are stable`() {
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.SAVE,
                PersistenceFailureCode.CONFLICT,
            ),
        ).isEqualTo("Workflow checkpoint conflict")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.LEASE,
                PersistenceOperation.CLAIM,
                PersistenceFailureCode.CONFLICT,
            ),
        ).isEqualTo("Workflow lease conflict")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.LOAD,
                PersistenceFailureCode.CORRUPTED_DATA,
            ),
        ).isEqualTo("Persisted workflow checkpoint is invalid")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.STEP_ATTEMPT,
                PersistenceOperation.LOAD,
                PersistenceFailureCode.CORRUPTED_DATA,
            ),
        ).isEqualTo("Persisted step-attempt record is invalid")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.LOAD,
                PersistenceFailureCode.READ_FAILED,
            ),
        ).isEqualTo("Workflow persistence read failed")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.SAVE,
                PersistenceFailureCode.WRITE_FAILED,
            ),
        ).isEqualTo("Workflow persistence write failed")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.DELETE,
                PersistenceFailureCode.DELETE_FAILED,
            ),
        ).isEqualTo("Workflow persistence delete failed")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.LIST,
                PersistenceFailureCode.LIST_FAILED,
            ),
        ).isEqualTo("Workflow persistence list failed")
    }

    // --- 15. Worker failAttempt sanitizes persistence failures, keeps user step errors ---

    @Test
    fun `worker failAttempt persists safe summary for persistence failures but keeps user step errors`() {
        // Mirrors the classifier the worker's failAttempt uses: a
        // persistence-family failure is sanitized for the durable outputSummary
        // and observer, while a user step-execution error keeps its message.
        val rawPersistence = WorkflowCheckpointCorruptionException("password=fixture-sentinel-7f3c")
        val safeSummary = summarizeForTest(rawPersistence)
        assertThat(safeSummary).doesNotContain("fixture-sentinel-7f3c")
        assertThat(safeSummary).doesNotContain("password=")

        val userError = IllegalStateException("user step failed: fixture-sentinel-7f3c")
        val userSummary = summarizeForTest(userError)
        assertThat(userSummary).contains("user step failed")
    }

    private fun summarizeForTest(error: Throwable): String {
        val observable = when {
            !error.isPersistenceFamilyFailure() -> error
            else -> safeWorkerObservableFailure(PersistenceResourceKind.STEP_ATTEMPT, PersistenceOperation.SAVE, error)
        }
        return buildString {
            append(observable::class.simpleName ?: observable::class.java.simpleName)
            val message = observable.message?.take(240)
            if (!message.isNullOrBlank()) {
                append(": ")
                append(message)
            }
        }
    }

    // --- fixtures ---

    private fun testCheckpoint() = WorkflowCheckpoint(
        workflowName = "wf",
        workflowId = "run-1",
        nextStepIndex = 0,
        stepExecutions = 0,
        lastCompletedStepName = null,
        statePayload = "state",
    )

    private fun minimalAttempt() = StepAttemptRecord(
        runId = "run-attempt",
        stepName = "work",
        attemptId = "attempt-1",
        workerId = "worker-a",
        leaseToken = "lease-a",
        status = StepAttemptStatus.STARTED,
        startedAt = 10L,
        replayPolicy = ReplayPolicy.PURE,
    )

    private class FailingCheckpointCatalog(
        private val failure: SQLException,
    ) : WorkflowCheckpointCatalog {
        override suspend fun listCheckpoints(): List<WorkflowCheckpoint> = throw failure
    }
}
