package dev.tramai.orchestration

import java.io.IOException
import java.io.PrintWriter
import java.nio.file.Files
import java.nio.file.Path
import java.sql.Connection
import java.sql.DatabaseMetaData
import java.sql.PreparedStatement
import java.sql.SQLException
import java.util.logging.Logger
import javax.sql.DataSource
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.cancel
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.catchThrowable
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

/**
 * Adversarial leak tests for the persistence safe-failure boundary (PR #225).
 *
 * The invariant: filesystem paths, SQL text, persisted payloads, and arbitrary
 * exception messages never cross from persistence internals into public
 * exceptions, ordinary observers, or logs. The original failure reaches only
 * [PersistenceFailureDiagnosticObserver]; cancellation stays cancellation.
 *
 * Secret fixtures use the value `fixture-sentinel-7f3c` (GitGuardian-safe:
 * no credential-shaped keys). Assertions scan message + cause + EVERY
 * suppressed throwable + observer events.
 */
class PersistenceSafeFailureBoundaryTest {

    @TempDir
    lateinit var tempDir: Path

    private companion object {
        const val SECRET_SQL = "UPDATE tramai_workflow SET state_payload = 'fixture-sentinel-7f3c'"
        const val SECRET_PATH = "/home/customer/acme/private/fixture-sentinel-7f3c/workflow"
        const val SECRET_PAYLOAD = "fixture-sentinel-7f3c-persisted-state"
        const val SECRET_VALUE = "fixture-sentinel-7f3c-value"
    }

    private class RecordingPersistenceObserver : PersistenceFailureDiagnosticObserver {
        val events = mutableListOf<PersistenceFailureDiagnosticEvent>()
        var throwAfterRecording: Throwable? = null
        var throwFakeCancellation: Boolean = false

        override suspend fun onFailure(event: PersistenceFailureDiagnosticEvent) {
            events += event
            if (throwFakeCancellation) throw CancellationException("synthetic observer cancellation")
            throwAfterRecording?.let { throw it }
        }
    }

    private fun assertNoSecret(t: Throwable?, secret: String, seen: MutableSet<Throwable> = mutableSetOf()) {
        if (t == null || !seen.add(t)) return
        assertThat(t.message).doesNotContain(secret)
        assertThat(t.toString()).doesNotContain(secret)
        assertNoSecret(t.cause, secret, seen)
        t.suppressed.forEach { assertNoSecret(it, secret, seen) }
    }

    /** DataSource whose Connection throws a seeded SQLException on any statement. */
    private class SeededSqlDataSource(
        private val failure: SQLException,
    ) : DataSource {
        override fun getConnection(): Connection = ThrowingConnection(failure)
        override fun getConnection(username: String?, password: String?): Connection = ThrowingConnection(failure)
        override fun getLogWriter(): PrintWriter? = null
        override fun setLogWriter(out: PrintWriter?) = Unit
        override fun setLoginTimeout(seconds: Int) = Unit
        override fun getLoginTimeout(): Int = 0
        override fun getParentLogger(): Logger = Logger.getGlobal()
        override fun <T : Any?> unwrap(iface: Class<T>?): T = throw SQLException("Unsupported")
        override fun isWrapperFor(iface: Class<*>?): Boolean = false
    }

    private class ThrowingConnection(
        private val failure: SQLException,
    ) : Connection {
        override fun prepareStatement(sql: String): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, columnIndexes: IntArray?): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, columnNames: Array<out String>?): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement = throw failure
        override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): PreparedStatement = throw failure
        override fun prepareCall(sql: String): java.sql.CallableStatement = throw failure
        override fun prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): java.sql.CallableStatement = throw failure
        override fun prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): java.sql.CallableStatement = throw failure
        override fun createStatement(): java.sql.Statement = throw failure
        override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): java.sql.Statement = throw failure
        override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): java.sql.Statement = throw failure
        override fun nativeSQL(sql: String?): String = throw failure
        override fun setAutoCommit(autoCommit: Boolean) = Unit
        override fun getAutoCommit(): Boolean = true
        override fun commit() = Unit
        override fun rollback() = Unit
        override fun close() = Unit
        override fun isClosed(): Boolean = false
        override fun setReadOnly(readOnly: Boolean) = Unit
        override fun isReadOnly(): Boolean = true
        override fun setCatalog(catalog: String?) = Unit
        override fun getCatalog(): String? = null
        override fun setTransactionIsolation(level: Int) = Unit
        override fun getTransactionIsolation(): Int = Connection.TRANSACTION_READ_COMMITTED
        override fun getWarnings(): java.sql.SQLWarning? = null
        override fun clearWarnings() = Unit
        override fun setTypeMap(map: MutableMap<String, Class<*>>?) = Unit
        override fun getTypeMap(): MutableMap<String, Class<*>> = mutableMapOf()
        override fun setHoldability(holdability: Int) = Unit
        override fun getHoldability(): Int = java.sql.ResultSet.HOLD_CURSORS_OVER_COMMIT
        override fun setSavepoint(): java.sql.Savepoint = throw failure
        override fun setSavepoint(name: String?): java.sql.Savepoint = throw failure
        override fun rollback(savepoint: java.sql.Savepoint?) = Unit
        override fun releaseSavepoint(savepoint: java.sql.Savepoint?) = Unit
        override fun createClob(): java.sql.Clob = throw failure
        override fun createBlob(): java.sql.Blob = throw failure
        override fun createNClob(): java.sql.NClob = throw failure
        override fun createSQLXML(): java.sql.SQLXML = throw failure
        override fun isValid(timeout: Int): Boolean = true
        override fun setClientInfo(name: String?, value: String?) = Unit
        override fun setClientInfo(properties: java.util.Properties?) = Unit
        override fun getClientInfo(name: String?): String? = null
        override fun getClientInfo(): java.util.Properties = java.util.Properties()
        override fun createArrayOf(typeName: String?, elements: Array<out Any>?): java.sql.Array = throw failure
        override fun createStruct(typeName: String?, attributes: Array<out Any>?): java.sql.Struct = throw failure
        override fun setSchema(schema: String?) = Unit
        override fun getSchema(): String? = null
        override fun abort(executor: java.util.concurrent.Executor?) = Unit
        override fun setNetworkTimeout(executor: java.util.concurrent.Executor?, milliseconds: Int) = Unit
        override fun getNetworkTimeout(): Int = 0
        override fun getMetaData(): DatabaseMetaData = throw failure
        override fun <T : Any?> unwrap(iface: Class<T>?): T = throw SQLException("Unsupported")
        override fun isWrapperFor(iface: Class<*>?): Boolean = false
    }

    // --- 1. JDBC secret SQL reaches observer only ---

    @Test
    fun `raw jdbc exception containing secret sql reaches observer but not public exception`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val store = JdbcWorkflowCheckpointStore(SeededSqlDataSource(SQLException(SECRET_SQL)))
            store.persistenceFailureDiagnosticObserver = observer

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(observer.events).hasSize(1)
            val event = observer.events.single()
            assertThat(event.resourceKind).isEqualTo(PersistenceResourceKind.CHECKPOINT)
            assertThat(event.operation).isEqualTo(PersistenceOperation.SAVE)
            assertThat(event.failureCode).isEqualTo(PersistenceFailureCode.WRITE_FAILED)
            assertThat(event.failure.message).contains(SECRET_SQL)
        }
    }

    // --- 2. File exception secret path reaches observer only ---

    @Test
    fun `file exception containing secret path reaches observer but not public exception`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val failingWriter = AtomicFileWriter { _ -> throw IOException(SECRET_PATH) }
            val store = FileWorkflowCheckpointStore.forTest(tempDir, failingWriter)
            store.persistenceFailureDiagnosticObserver = observer

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_PATH)
            assertThat(observer.events).hasSize(1)
            assertThat(observer.events.single().failure.message).contains(SECRET_PATH)
        }
    }

    // --- 3. Corrupt checkpoint secret payload reaches observer only ---

    @Test
    fun `corrupt checkpoint containing secret payload reaches observer but not public exception`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val store = FileWorkflowCheckpointStore(tempDir)
            store.persistenceFailureDiagnosticObserver = observer
            // Write a checkpoint file whose recovery state decodes to garbage carrying the secret.
            val checkpointDir = tempDir.resolve("wf").resolve("run-1").toFile()
            checkpointDir.mkdirs()
            Files.writeString(
                tempDir.resolve("wf").resolve("run-1").resolve("checkpoint.properties"),
                "workflowName=wf\nworkflowId=run-1\nnextStepIndex=0\nstepExecutions=0\nstatePayloadBase64=c3RhdGU=\nrevision=1\nrecoveryState=${base64Encode(SECRET_PAYLOAD)}\n",
            )

            val thrown = catchThrowable {
                runBlocking { store.load("wf", "run-1") }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointCorruptionException::class.java)
            assertNoSecret(thrown, SECRET_PAYLOAD)
            assertThat(observer.events).hasSize(1)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.CORRUPTED_DATA)
        }
    }

    // --- 4. Corrupt step-attempt record secret value reaches observer only ---

    @Test
    fun `corrupt step attempt record containing secret value reaches observer but not public exception`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val store = FileStepAttemptRecordStore.forTest(tempDir, realAtomicFileWriter)
            store.persistenceFailureDiagnosticObserver = observer
            // Seed one record then corrupt its status to an unknown value carrying the secret.
            val record = minimalAttempt()
            store.recordStepAttempt(record)
            val attemptPath = tempDir
                .resolve(base64UrlEncodeNoPadding(record.runId))
                .resolve(base64UrlEncodeNoPadding(record.stepName))
                .resolve(base64UrlEncodeNoPadding(record.attemptId) + ".attempt.properties")
            val raw = Files.readString(attemptPath)
            Files.writeString(attemptPath, raw.replace("status=STARTED", "status=$SECRET_VALUE"))

            val thrown = catchThrowable {
                runBlocking { store.listStepAttempts(record.runId) }
            }

            assertThat(thrown).isInstanceOf(StepAttemptRecordCorruptionException::class.java)
            assertNoSecret(thrown, SECRET_VALUE)
            assertThat(observer.events).hasSize(1)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.CORRUPTED_DATA)
        }
    }

    // --- 5. Untrusted caller-constructed domain exception is re-sanitized ---

    @Test
    fun `caller constructed untrusted domain exception is re sanitized`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val untrusted = WorkflowCheckpointCorruptionException("password=fixture-sentinel-7f3c")

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(
                        PersistenceResourceKind.CHECKPOINT,
                        PersistenceOperation.LOAD,
                        observer,
                    ) { throw untrusted }
                }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointCorruptionException::class.java)
            assertThat(thrown).isNotSameAs(untrusted)
            assertNoSecret(thrown, "password=")
            assertNoSecret(thrown, "fixture-sentinel-7f3c")
            assertThat(observer.events).hasSize(1)
            assertThat(observer.events.single().failure).isSameAs(untrusted)
        }
    }

    // --- 6. Trusted safe exceptions are reconstructed ---

    @Test
    fun `trusted safe exception is reconstructed without observer event`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val safe = safePersistenceFailure(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.SAVE,
                PersistenceFailureCode.CONFLICT,
            )

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(
                        PersistenceResourceKind.CHECKPOINT,
                        PersistenceOperation.SAVE,
                        observer,
                    ) { throw safe }
                }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointConflictException::class.java)
            assertThat(thrown).isNotSameAs(safe)
            assertThat(thrown!!.cause).isNull()
            assertThat(thrown.suppressed).isEmpty()
            assertThat(observer.events).isEmpty()
        }
    }

    @Test
    fun `cancellation with suppressed sql is sanitized for the caller`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val cancelled = CancellationException("parent cancelled").also { it.addSuppressed(SQLException(SECRET_SQL)) }

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.SAVE, observer) {
                        throw cancelled
                    }
                }
            }

            assertThat(thrown).isInstanceOf(CancellationException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            // Genuine-cancellation path: no observer delivery (delivery's
            // postcondition ensureActive() would throw under parent cancellation),
            // only the sanitized CE with the fixed cleanup marker.
            assertThat(observer.events).isEmpty()
            assertThat(thrown!!.suppressed.single()).isInstanceOf(PersistenceCleanupDiagnosticException::class.java)
        }
    }

    @Test
    fun `cancellation with cause and suppressed sql is sanitized for the caller`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val cancelled = CancellationException("close $SECRET_SQL").also { it.addSuppressed(SQLException("rollback $SECRET_SQL")) }

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.SAVE, observer) {
                        throw cancelled
                    }
                }
            }

            assertThat(thrown).isInstanceOf(CancellationException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(observer.events).isEmpty()
            assertThat(thrown!!.suppressed.single()).isInstanceOf(PersistenceCleanupDiagnosticException::class.java)
        }
    }

    @Test
    fun `nested cancellation with raw suppressed sql in cause graph is sanitized for the caller`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val inner = CancellationException("inner").also { it.addSuppressed(SQLException(SECRET_SQL)) }
            val outer = CancellationException("outer").also { it.initCause(inner) }

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.SAVE, observer) {
                        throw outer
                    }
                }
            }

            assertThat(thrown).isInstanceOf(CancellationException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(observer.events).isEmpty()
            assertThat(thrown!!.suppressed.single()).isInstanceOf(PersistenceCleanupDiagnosticException::class.java)
        }
    }

    @Test
    fun `trusted exception contaminated by jdbc cleanup is reconstructed not passed through`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val trusted = safePersistenceFailure(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.SAVE, PersistenceFailureCode.CONFLICT)
                .also { it.addSuppressed(SQLException(SECRET_SQL)) }

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.SAVE, observer) { throw trusted }
                }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointConflictException::class.java)
            assertThat(thrown).isNotSameAs(trusted)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(thrown!!.cause).isNull()
            assertThat(thrown.suppressed).isEmpty()
            assertThat(observer.events.single().failure).isSameAs(trusted)
        }
    }

    @Test
    fun `throwing path strategy in file lease release is caught by boundary`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val store = FileWorkflowLeaseStore(tempDir, throwingPathStrategy(), { 0L }, observer)
            val thrown = catchThrowable { runBlocking { store.release(testLease()) } }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_PATH)
            assertThat(observer.events).hasSize(1)
        }
    }

    @Test
    fun `throwing path strategy in file fenced delete is caught by boundary`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val store = FileWorkflowLeaseStore(tempDir, throwingPathStrategy(), { 0L }, observer)
            val thrown = catchThrowable {
                runBlocking { store.deleteCheckpointIfLeaseOwner(InMemoryWorkflowCheckpointStore(), "wf", "run-1", null, testLease()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_PATH)
            assertThat(observer.events).hasSize(1)
        }
    }

    @Test
    fun `requireRecovery load failure is classified read failed not write failed`() {
        runBlocking {
            // Explicit implementation (no `by` delegation): the interface default
            // requireRecovery must call THIS load() and fail with the raw error.
            val store = FailingLoadCheckpointStore(InMemoryWorkflowCheckpointStore(), IOException(SECRET_PATH))
            val thrown = catchThrowable { runBlocking { store.requireRecovery("wf", "run-1", 1, testRecoveryRecord()) } }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertThat(thrown!!.message).isEqualTo("Workflow persistence read failed")
            assertNoSecret(thrown, SECRET_PATH)
        }
    }

    @Test
    fun `clearRecovery load failure is classified read failed not write failed`() {
        runBlocking {
            val store = FailingLoadCheckpointStore(InMemoryWorkflowCheckpointStore(), IOException(SECRET_PATH))
            val thrown = catchThrowable { runBlocking { store.clearRecovery("wf", "run-1", 1) } }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertThat(thrown!!.message).isEqualTo("Workflow persistence read failed")
            assertNoSecret(thrown, SECRET_PATH)
        }
    }

    @Test
    fun `lease delete phase inside load is classified delete failed`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.LEASE, PersistenceOperation.LOAD, observer) {
                        throw LeaseDeletePhaseFailure(IOException(SECRET_PATH))
                    }
                }
            }
            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_PATH)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.DELETE_FAILED)
            assertThat(observer.events.single().operation).isEqualTo(PersistenceOperation.LOAD)
        }
    }

    @Test
    fun `updateHeartbeat check and update stay atomic against unregister`() {
        runBlocking {
            val store = InMemoryWorkflowLeaseStore(
                clockMillis = { 1000L },
                observer = RecordingPersistenceObserver(),
            )
            store.registerWorker("w1", "pool", "v1", setOf(), "host")
            // Concurrent heartbeats and unregisters; the observable outcomes are
            // only success or IllegalArgumentException (unknown worker) — never
            // NoSuchElementException or a persistence failure from a
            // check-then-act race.
            val errors = java.util.Collections.synchronizedList(mutableListOf<Throwable>())
            val jobs = (1..8).map { worker ->
                launch {
                    repeat(100) { i ->
                        if (i % 2 == 0) {
                            try {
                                store.updateHeartbeat("w1")
                            } catch (t: Throwable) {
                                errors.add(t)
                            }
                            store.registerWorker("w1", "pool", "v1", setOf(), "host")
                        } else {
                            // Genuine unregister: the next heartbeat either sees
                            // the worker (re-registered by an even iteration) or
                            // fails with IllegalArgumentException — never a
                            // NoSuchElementException from a check-then-act race.
                            store.unregisterWorker("w1")
                            try {
                                store.updateHeartbeat("w1")
                            } catch (t: Throwable) {
                                errors.add(t)
                            }
                            store.registerWorker("w1", "pool", "v1", setOf(), "host")
                        }
                    }
                }
            }
            jobs.forEach { it.join() }
            errors.forEach { assertThat(it).isInstanceOf(IllegalArgumentException::class.java) }
        }
    }

    @Test
    fun `updateHeartbeat unknown worker throws IllegalArgumentException not persistence failure`() {
        runBlocking {
            val store = InMemoryWorkflowLeaseStore(
                clockMillis = { 1000L },
                observer = RecordingPersistenceObserver(),
            )
            val thrown = catchThrowable { runBlocking { store.updateHeartbeat("unknown") } }
            assertThat(thrown).isInstanceOf(IllegalArgumentException::class.java)
        }
    }

    @Test
    fun `negative stale threshold throws IllegalArgumentException not persistence failure`() {
        runBlocking {
            val store = InMemoryWorkflowLeaseStore(
                clockMillis = { 1000L },
                observer = RecordingPersistenceObserver(),
            )
            val thrown = catchThrowable { runBlocking { store.listStaleWorkers(-1) } }
            assertThat(thrown).isInstanceOf(IllegalArgumentException::class.java)
        }
    }

    @Test
    fun `lease delete phase inside renew is classified delete failed`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.LEASE, PersistenceOperation.RENEW, observer) {
                        throw LeaseDeletePhaseFailure(IOException(SECRET_PATH))
                    }
                }
            }
            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_PATH)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.DELETE_FAILED)
            assertThat(observer.events.single().operation).isEqualTo(PersistenceOperation.RENEW)
        }
    }

    @Test
    fun `lease read phase inside claim is classified read failed`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.LEASE, PersistenceOperation.CLAIM, observer) {
                        throw LeaseReadPhaseFailure(IOException(SECRET_PATH))
                    }
                }
            }
            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_PATH)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.READ_FAILED)
            assertThat(observer.events.single().operation).isEqualTo(PersistenceOperation.CLAIM)
        }
    }

    private class FailingLoadCheckpointStore(
        private val delegate: InMemoryWorkflowCheckpointStore,
        private val failure: Throwable,
    ) : WorkflowCheckpointStore {
        override suspend fun load(workflowName: String, workflowId: String): WorkflowCheckpoint? = throw failure
        override suspend fun save(checkpoint: WorkflowCheckpoint, expectedRevision: Long?): WorkflowCheckpoint =
            delegate.save(checkpoint, expectedRevision)
        override suspend fun delete(
            workflowName: String,
            workflowId: String,
            expectedRevision: Long?,
            expectedGeneration: String?,
        ) = delegate.delete(workflowName, workflowId, expectedRevision, expectedGeneration)
    }

    @Test
    fun `raw conflict named exception uses operation default rather than name heuristic`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.SAVE, observer) {
                        throw IllegalStateException("Conflict-ish")
                    }
                }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.WRITE_FAILED)
        }
    }

    @Test
    fun `checkpoint dml failure reaches checkpoint observer not lease observer`() {
        runBlocking {
            val checkpointObserver = RecordingPersistenceObserver()
            val leaseObserver = RecordingPersistenceObserver()
            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(
                        PersistenceResourceKind.LEASE,
                        PersistenceOperation.SAVE,
                        leaseObserver,
                        checkpointDiagnosticObserver = checkpointObserver,
                    ) { throw CheckpointDmlFailure(SQLException(SECRET_SQL)) }
                }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(checkpointObserver.events.single().resourceKind).isEqualTo(PersistenceResourceKind.CHECKPOINT)
            assertThat(leaseObserver.events).isEmpty()
        }
    }

    @Test
    fun `sanitized cancellation escapes even when coroutine context is already cancelled`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val contaminated = CancellationException("parent").also { it.addSuppressed(SQLException(SECRET_SQL)) }
            val outer = CoroutineScope(Job())
            val outcome = CompletableDeferred<Throwable?>()

            outer.launch {
                try {
                    persistenceBoundary(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.SAVE, observer) {
                        currentCoroutineContext().cancel()
                        throw contaminated
                    }
                    outcome.complete(null)
                } catch (error: Throwable) {
                    outcome.complete(error)
                }
            }

            val terminal = withTimeout(5_000) { outcome.await() }
            assertThat(terminal).isInstanceOf(CancellationException::class.java)
            assertNoSecret(terminal, SECRET_SQL)
            assertThat(terminal!!.suppressed).hasSize(1)
            assertThat(terminal.suppressed.single()).isInstanceOf(PersistenceCleanupDiagnosticException::class.java)
            assertThat(observer.events).isEmpty()
        }
    }

    @Test
    fun `corrupt checkpoint inside fenced dml is classified corrupted data`() {
        runBlocking {
            val checkpointObserver = RecordingPersistenceObserver()
            val leaseObserver = RecordingPersistenceObserver()
            val corrupt = CorruptCheckpointException("corrupt", "payload-$SECRET_SQL")

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(
                        PersistenceResourceKind.LEASE,
                        PersistenceOperation.SAVE,
                        leaseObserver,
                        checkpointDiagnosticObserver = checkpointObserver,
                    ) { throw CheckpointDmlFailure(corrupt) }
                }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointCorruptionException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(checkpointObserver.events.single().failureCode).isEqualTo(PersistenceFailureCode.CORRUPTED_DATA)
            assertThat(leaseObserver.events).isEmpty()
        }
    }

    @Test
    fun `external diagnostic observer reads corrupt payload through public interface`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val corrupt = CorruptCheckpointException("corrupt", "payload-$SECRET_SQL")

            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.LOAD, observer) {
                        throw corrupt
                    }
                }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointCorruptionException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            val detail = observer.events.single().failure as? PersistenceCorruptionDetail
            assertThat(detail).isNotNull
            assertThat(detail!!.corruptPayload).contains(SECRET_SQL)
        }
    }

    @Test
    fun `fenced jdbc save preconditions remain caller errors`() {
        runBlocking {
            val leaseStore = JdbcWorkflowLeaseStore(SeededSqlDataSource(SQLException(SECRET_SQL)))
            val nonJdbc = catchThrowable {
                runBlocking {
                    leaseStore.saveCheckpointIfLeaseOwner(InMemoryWorkflowCheckpointStore(), testCheckpoint(), null, testLease())
                }
            }
            val mismatched = catchThrowable {
                runBlocking {
                    leaseStore.saveCheckpointIfLeaseOwner(
                        JdbcWorkflowCheckpointStore(SeededSqlDataSource(SQLException(SECRET_SQL))),
                        testCheckpoint(),
                        null,
                        testLease(),
                    )
                }
            }

            assertThat(nonJdbc).isInstanceOf(IllegalArgumentException::class.java)
            assertThat(mismatched).isInstanceOf(IllegalArgumentException::class.java)
        }
    }

    @Test
    fun `in memory lease caller preconditions remain caller errors`() {
        runBlocking {
            val store = InMemoryWorkflowLeaseStore()
            val unknownWorker = catchThrowable { runBlocking { store.updateHeartbeat("unknown") } }
            val negativeThreshold = catchThrowable { runBlocking { store.listStaleWorkers(-1) } }

            assertThat(unknownWorker).isInstanceOf(IllegalArgumentException::class.java)
            assertThat(negativeThreshold).isInstanceOf(IllegalArgumentException::class.java)
        }
    }

    @Test
    fun `jdbc lease claim read failure is classified read failed not write failed`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val store = JdbcWorkflowLeaseStore(SeededSqlDataSource(SQLException(SECRET_SQL)))
            store.persistenceFailureDiagnosticObserver = observer

            val thrown = catchThrowable {
                runBlocking { store.claim("wf", "run-1", "owner", null, 1_000) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.READ_FAILED)
            assertThat(observer.events.single().operation).isEqualTo(PersistenceOperation.CLAIM)
        }
    }

    @Test
    fun `lease renew read failure preserves renew operation`() {
        assertLeaseReadFailure(PersistenceOperation.RENEW)
    }

    @Test
    fun `lease release read failure preserves release operation`() {
        assertLeaseReadFailure(PersistenceOperation.RELEASE)
    }

    private fun assertLeaseReadFailure(operation: PersistenceOperation) {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val thrown = catchThrowable {
                runBlocking {
                    persistenceBoundary(PersistenceResourceKind.LEASE, operation, observer) {
                        throw LeaseReadPhaseFailure(IOException(SECRET_PATH))
                    }
                }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_PATH)
            assertThat(observer.events.single().failureCode).isEqualTo(PersistenceFailureCode.READ_FAILED)
            assertThat(observer.events.single().operation).isEqualTo(operation)
        }
    }

    @Test
    fun `trusted failure cannot beat concurrent genuine cancellation`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val entered = CompletableDeferred<Unit>()
            val release = CompletableDeferred<Unit>()
            val outer = CoroutineScope(Job())
            val outcome = CompletableDeferred<Throwable?>()
            outer.launch {
                try {
                    persistenceBoundary(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.SAVE, observer) {
                        entered.complete(Unit)
                        release.await()
                        throw safePersistenceFailure(PersistenceResourceKind.CHECKPOINT, PersistenceOperation.SAVE, PersistenceFailureCode.CONFLICT)
                    }
                    outcome.complete(null)
                } catch (t: Throwable) {
                    outcome.complete(t)
                }
            }
            entered.await()
            outer.coroutineContext[Job]!!.cancel()
            release.complete(Unit)

            assertThat(withTimeout(5_000) { outcome.await() }).isInstanceOf(CancellationException::class.java)
            assertThat(observer.events).isEmpty()
        }
    }

    // --- 7. Observer ordinary failure is fail-open ---

    @Test
    fun `observer ordinary failure is fail open`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            observer.throwAfterRecording = IllegalStateException("observer bug")
            val store = JdbcWorkflowCheckpointStore(SeededSqlDataSource(SQLException(SECRET_SQL)))
            store.persistenceFailureDiagnosticObserver = observer

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(observer.events).hasSize(1)
        }
    }

    // --- 8. Synthetic observer cancellation while active is swallowed ---

    @Test
    fun `synthetic observer cancellation while active does not replace failure`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            observer.throwFakeCancellation = true
            val store = JdbcWorkflowCheckpointStore(SeededSqlDataSource(SQLException(SECRET_SQL)))
            store.persistenceFailureDiagnosticObserver = observer

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(thrown, SECRET_SQL)
            assertThat(observer.events).hasSize(1)
        }
    }

    // --- 9. Genuine parent cancellation stays primary, emits no diagnostic ---

    @Test
    fun `genuine parent cancellation remains primary and emits no diagnostic`() {
        runBlocking {
            val observer = RecordingPersistenceObserver()
            val entered = CompletableDeferred<Unit>()
            val release = CompletableDeferred<Unit>()

            val outer = CoroutineScope(Job())
            val outcome = CompletableDeferred<Throwable?>()
            outer.launch {
                try {
                    persistenceBoundary(
                        PersistenceResourceKind.CHECKPOINT,
                        PersistenceOperation.SAVE,
                        observer,
                    ) {
                        entered.complete(Unit)
                        release.await()
                        Unit
                    }
                    outcome.complete(null)
                } catch (t: Throwable) {
                    outcome.complete(t)
                }
            }
            entered.await()
            outer.coroutineContext[Job]!!.cancel()
            release.complete(Unit)
            val terminal = withTimeout(5_000) { outcome.await() }
            assertThat(terminal).isInstanceOf(CancellationException::class.java)
            assertThat(observer.events).isEmpty()
        }
    }

    // --- 10. Checkpoint conflict keeps its semantic class ---

    @Test
    fun `checkpoint conflict remains the correct semantic exception class`() {
        runBlocking {
            val store = InMemoryWorkflowCheckpointStore()
            store.save(testCheckpoint())

            val thrown = catchThrowable {
                runBlocking { store.save(testCheckpoint()) }
            }

            assertThat(thrown).isInstanceOf(WorkflowCheckpointConflictException::class.java)
            assertThat((thrown as WorkflowCheckpointConflictException).message).isEqualTo("Workflow checkpoint conflict")
            assertThat((thrown as WorkflowCheckpointConflictException).cause).isNull()
        }
    }

    // --- 11. CAS and revision behavior unchanged ---

    @Test
    fun `cas and revision behavior unchanged`() {
        runBlocking {
            val store = InMemoryWorkflowCheckpointStore()
            val first = store.save(testCheckpoint())
            assertThat(first.revision).isEqualTo(1)

            val second = store.save(first, expectedRevision = first.revision)
            assertThat(second.revision).isEqualTo(2)

            val conflict = catchThrowable {
                runBlocking { store.save(second, expectedRevision = first.revision) }
            }
            assertThat(conflict).isInstanceOf(WorkflowCheckpointConflictException::class.java)

            val attemptStore = store as StepAttemptRecordStore
            val attempt = minimalAttempt()
            attemptStore.recordStepAttempt(attempt)
            assertThat(attemptStore.compareAndSetStepAttempt(attempt, attempt.copy(workerId = "w2"))).isTrue()
            assertThat(attemptStore.compareAndSetStepAttempt(attempt, attempt.copy(workerId = "w3"))).isFalse()
        }
    }

    // --- 12. Worker onPollFailed receives only the safe failure ---

    @Test
    fun `worker onPollFailed receives only safe failure`() {
        val pollFailures = mutableListOf<Throwable>()
        val workerObserver = object : TramaiWorkerObserver {
            override fun onPollFailed(workerId: String, error: Throwable) {
                pollFailures += error
            }
        }
        val failingCatalog = FailingCheckpointCatalog(SQLException(SECRET_SQL))
        val checkpointStore = InMemoryWorkflowCheckpointStore()

        val worker = TramaiWorker(
            config = WorkerConfig(
                workerId = "worker-secret-test",
                poolName = "tests",
                pollIntervalMillis = 20,
                leaseDurationMillis = 200,
                drainTimeoutMillis = 1_000,
                partitionEnabled = false,
                workerCount = 1,
            ),
            leaseStore = InMemoryWorkflowLeaseStore(),
            checkpointStore = checkpointStore,
            checkpointCatalog = failingCatalog,
            stepAttemptStore = checkpointStore,
            workflowBindings = WorkflowBindingRegistry {},
            observability = workerObserver,
        )
        runBlocking {
            worker.start()
            try {
                withTimeout(5_000) {
                    while (pollFailures.isEmpty() && currentCoroutineContext().isActive) delay(20)
                }
            } finally {
                worker.shutdown()
            }
        }

        assertThat(pollFailures).isNotEmpty()
        pollFailures.forEach { failure ->
            assertThat(failure).isInstanceOf(WorkflowPersistenceFailureException::class.java)
            assertNoSecret(failure, SECRET_SQL)
        }
    }

    // --- 13. Logging observer renders class name only ---

    @Test
    fun `logging observer renders no raw error message`() {
        val logged = mutableListOf<String>()
        val observer = LoggingTramaiWorkerObserver { logged += it }
        observer.onPollFailed("w", SQLException(SECRET_SQL))
        observer.onLeaseRenewalFailed("wf", "w", IOException(SECRET_PATH))
        assertThat(logged.joinToString("\n")).doesNotContain(SECRET_SQL)
        assertThat(logged.joinToString("\n")).doesNotContain(SECRET_PATH)
    }

    // --- 14. Fixed public messages are stable ---

    @Test
    fun `fixed public messages are stable`() {
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.SAVE,
                PersistenceFailureCode.CONFLICT,
            ),
        ).isEqualTo("Workflow checkpoint conflict")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.LEASE,
                PersistenceOperation.CLAIM,
                PersistenceFailureCode.CONFLICT,
            ),
        ).isEqualTo("Workflow lease conflict")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.LOAD,
                PersistenceFailureCode.CORRUPTED_DATA,
            ),
        ).isEqualTo("Persisted workflow checkpoint is invalid")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.STEP_ATTEMPT,
                PersistenceOperation.LOAD,
                PersistenceFailureCode.CORRUPTED_DATA,
            ),
        ).isEqualTo("Persisted step-attempt record is invalid")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.LOAD,
                PersistenceFailureCode.READ_FAILED,
            ),
        ).isEqualTo("Workflow persistence read failed")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.SAVE,
                PersistenceFailureCode.WRITE_FAILED,
            ),
        ).isEqualTo("Workflow persistence write failed")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.DELETE,
                PersistenceFailureCode.DELETE_FAILED,
            ),
        ).isEqualTo("Workflow persistence delete failed")
        assertThat(
            fixedPersistenceFailureMessage(
                PersistenceResourceKind.CHECKPOINT,
                PersistenceOperation.LIST,
                PersistenceFailureCode.LIST_FAILED,
            ),
        ).isEqualTo("Workflow persistence list failed")
    }

    // --- 15. Worker failAttempt sanitizes persistence failures, keeps user step errors ---

    @Test
    fun `worker failAttempt persists safe summary for persistence failures but keeps user step errors`() {
        // Mirrors the classifier the worker's failAttempt uses: a
        // persistence-family failure is sanitized for the durable outputSummary
        // and observer, while a user step-execution error keeps its message.
        val rawPersistence = WorkflowCheckpointCorruptionException("password=fixture-sentinel-7f3c")
        val safeSummary = summarizeForTest(rawPersistence)
        assertThat(safeSummary).doesNotContain("fixture-sentinel-7f3c")
        assertThat(safeSummary).doesNotContain("password=")

        val userError = IllegalStateException("user step failed: fixture-sentinel-7f3c")
        val userSummary = summarizeForTest(userError)
        assertThat(userSummary).contains("user step failed")
    }

    private fun summarizeForTest(error: Throwable): String {
        val observable = when {
            !error.isPersistenceFamilyFailure() -> error
            else -> safeWorkerObservableFailure(PersistenceResourceKind.STEP_ATTEMPT, PersistenceOperation.SAVE, error)
        }
        return buildString {
            append(observable::class.simpleName ?: observable::class.java.simpleName)
            val message = observable.message?.take(240)
            if (!message.isNullOrBlank()) {
                append(": ")
                append(message)
            }
        }
    }

    // --- fixtures ---

    private fun testCheckpoint() = WorkflowCheckpoint(
        workflowName = "wf",
        workflowId = "run-1",
        nextStepIndex = 0,
        stepExecutions = 0,
        lastCompletedStepName = null,
        statePayload = "state",
    )

    private fun testLease() = WorkflowLease(
        workflowName = "wf",
        workflowId = "run-1",
        leaseId = "lease-1",
        ownerId = "owner-1",
        checkpointRevision = null,
        acquiredAtEpochMillis = 0,
        expiresAtEpochMillis = 1_000,
    )

    private fun throwingPathStrategy() = object : WorkflowCheckpointPathStrategy {
        override fun resolve(root: Path, workflowName: String, workflowId: String): Path = throw IOException(SECRET_PATH)
    }

    private fun testRecoveryRecord() = WorkflowRecoveryRecord(
        reason = WorkflowRecoveryReason.NON_REPLAYABLE_OUTCOME_UNKNOWN,
        stepName = "step",
        attemptId = "attempt",
        priorWorkerId = "worker",
        detectedAtEpochMillis = 0,
    )

    private fun minimalAttempt() = StepAttemptRecord(
        runId = "run-attempt",
        stepName = "work",
        attemptId = "attempt-1",
        workerId = "worker-a",
        leaseToken = "lease-a",
        status = StepAttemptStatus.STARTED,
        startedAt = 10L,
        replayPolicy = ReplayPolicy.PURE,
    )

    private class FailingCheckpointCatalog(
        private val failure: SQLException,
    ) : WorkflowCheckpointCatalog {
        override suspend fun listCheckpoints(): List<WorkflowCheckpoint> = throw failure
    }
}
